# Generated by Django 3.1.1 on 2020-09-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=250)),
                ('principle', models.FloatField()),
                ('current_balance', models.FloatField()),
                ('apr', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.loan')),
            ],
        ),
    ]
